### ISSUE TITLE
Unexpected token %=

### ISSUE THREAD

**Issue by flq** [robksawyer/generator-durandal#1]
After the question `Which features do you want to include in your application?`, the generator dies on me with

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: Unexpected token %=
    at Function (native)
    at Function.template (/Users/flq/.nvm/v0.11.13/lib/node_modules/generator-durandal/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22)
    at copy.process (/Users/flq/.nvm/v0.11.13/lib/node_modules/generator-durandal/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:11:16)
    at applyProcessingFunc (/Users/flq/.nvm/v0.11.13/lib/node_modules/generator-durandal/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:11:16)
    at EditionInterface.exports._copySingle (/Users/flq/.nvm/v0.11.13/lib/node_modules/generator-durandal/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:51:24)
    at EditionInterface.exports.copy (/Users/flq/.nvm/v0.11.13/lib/node_modules/generator-durandal/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/flq/.nvm/v0.11.13/lib/node_modules/generator-durandal/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:9:8)
    at DurandalGenerator.template (/Users/flq/.nvm/v0.11.13/lib/node_modules/generator-durandal/node_modules/yeoman-generator/lib/actions/actions.js:191:11)
    at DurandalGenerator.gruntfile (/Users/flq/.nvm/v0.11.13/lib/node_modules/generator-durandal/app/index.js:114:10)
    at /Users/flq/.nvm/v0.11.13/lib/node_modules/generator-durandal/node_modules/yeoman-generator/lib/base.js:409:16
```

**Comment by flq** [comment]
Look, I'm closing your last issue :D
